# theme.toml Configuration file for Minimal-Blank

name = "Minimal Blank"
license = "MIT"
licenselink = "https://github.com/egeorjon/Minimal-Blank/blob/main/LICENSE"
description = "Hugo minimalist theme for a personal blog"
homepage = "https://github.com/egeorjon/Minimal-Blank/"
tags = [ "minimal", "blank", "bootstrap", "FontAwesome" ]
features = []
min_version = "0.81.0"

[author]
  name = "Emmanuel GEORJON"
  homepage = "http://www.emmanuelgeorjon.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
